### PR TITLE
Generate and upload AppImage

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

cc @zdenop @marathone

### CODE REVIEW

**Comment by probonopd** [comment]
An AppImage for testing is available at https://github.com/probonopd/scantailor-advanced/releases.

**Comment by 4lex4** [comment]
Rejected due to #69, #124 

Resume:
1. Qt theming is broken if AppImage is launched in environment different from that it was built on.
2. Qt High DPI displays support doesn't work with AppImage.

**Comment by probonopd** [comment]
Then we should fix those things, shouldn't we @4lex4? ;-)

> Qt theming is broken if AppImage is launched in an environment different from that it was built on.

Cosmetic, hardly a reason not to offer an AppImage. With some fine-tuning, it can probably be made work if we know what "broken" exactly is referring to. For example, the Scribus (also Qt based) AppImage theming looks very native on a Xubuntu (Gtk) system

> The same for Qt High DPI displays support

Please elaborate. How can I test this?

I wonder whether the Scribus AppImage is exhibiting the same issues.

**Comment by aoloe** [comment]
i have the feeling that the appimage behaves correctly in an hdpi setting.

but since i have custom settings in place to run the _normal_ scribus i think that i'm not the right one to judge about it.

**Pull request closed without merging**
